// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package proxy

import (
	server "github.com/authzed/spicedb/pkg/cmd/server"
	defaults "github.com/creasty/defaults"
)

type SpiceDBOptionsOption func(s *SpiceDBOptions)

// NewSpiceDBOptionsWithOptions creates a new SpiceDBOptions with the passed in options set
func NewSpiceDBOptionsWithOptions(opts ...SpiceDBOptionsOption) *SpiceDBOptions {
	s := &SpiceDBOptions{}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// NewSpiceDBOptionsWithOptionsAndDefaults creates a new SpiceDBOptions with the passed in options set starting from the defaults
func NewSpiceDBOptionsWithOptionsAndDefaults(opts ...SpiceDBOptionsOption) *SpiceDBOptions {
	s := &SpiceDBOptions{}
	defaults.MustSet(s)
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// ToOption returns a new SpiceDBOptionsOption that sets the values from the passed in SpiceDBOptions
func (s *SpiceDBOptions) ToOption() SpiceDBOptionsOption {
	return func(to *SpiceDBOptions) {
		to.SpiceDBEndpoint = s.SpiceDBEndpoint
		to.EmbeddedSpiceDB = s.EmbeddedSpiceDB
		to.BootstrapContent = s.BootstrapContent
		to.Insecure = s.Insecure
		to.SkipVerifyCA = s.SkipVerifyCA
		to.SecureSpiceDBTokensBySpace = s.SecureSpiceDBTokensBySpace
		to.SpicedbCAPath = s.SpicedbCAPath
	}
}

// DebugMap returns a map form of SpiceDBOptions for debugging
func (s *SpiceDBOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if s.SpiceDBEndpoint == "" {
		debugMap["SpiceDBEndpoint"] = "(empty)"
	} else {
		debugMap["SpiceDBEndpoint"] = s.SpiceDBEndpoint
	}
	debugMap["Insecure"] = "(sensitive)"
	debugMap["SkipVerifyCA"] = s.SkipVerifyCA
	if s.SecureSpiceDBTokensBySpace == "" {
		debugMap["SecureSpiceDBTokensBySpace"] = "(empty)"
	} else {
		debugMap["SecureSpiceDBTokensBySpace"] = "(sensitive)"
	}
	if s.SpicedbCAPath == "" {
		debugMap["SpicedbCAPath"] = "(empty)"
	} else {
		debugMap["SpicedbCAPath"] = s.SpicedbCAPath
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of SpiceDBOptions for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (s *SpiceDBOptions) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(s.DebugMap())
}

// SpiceDBOptionsWithOptions configures an existing SpiceDBOptions with the passed in options set
func SpiceDBOptionsWithOptions(s *SpiceDBOptions, opts ...SpiceDBOptionsOption) *SpiceDBOptions {
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// WithOptions configures the receiver SpiceDBOptions with the passed in options set
func (s *SpiceDBOptions) WithOptions(opts ...SpiceDBOptionsOption) *SpiceDBOptions {
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// WithSpiceDBEndpoint returns an option that can set SpiceDBEndpoint on a SpiceDBOptions
func WithSpiceDBEndpoint(spiceDBEndpoint string) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.SpiceDBEndpoint = spiceDBEndpoint
	}
}

// WithEmbeddedSpiceDB returns an option that can set EmbeddedSpiceDB on a SpiceDBOptions
func WithEmbeddedSpiceDB(embeddedSpiceDB server.RunnableServer) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.EmbeddedSpiceDB = embeddedSpiceDB
	}
}

// WithBootstrapContent returns an option that can append BootstrapContents to SpiceDBOptions.BootstrapContent
func WithBootstrapContent(key string, value []byte) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.BootstrapContent[key] = value
	}
}

// SetBootstrapContent returns an option that can set BootstrapContent on a SpiceDBOptions
func SetBootstrapContent(bootstrapContent map[string][]byte) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.BootstrapContent = bootstrapContent
	}
}

// WithInsecure returns an option that can set Insecure on a SpiceDBOptions
func WithInsecure(insecure bool) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.Insecure = insecure
	}
}

// WithSkipVerifyCA returns an option that can set SkipVerifyCA on a SpiceDBOptions
func WithSkipVerifyCA(skipVerifyCA bool) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.SkipVerifyCA = skipVerifyCA
	}
}

// WithSecureSpiceDBTokensBySpace returns an option that can set SecureSpiceDBTokensBySpace on a SpiceDBOptions
func WithSecureSpiceDBTokensBySpace(secureSpiceDBTokensBySpace string) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.SecureSpiceDBTokensBySpace = secureSpiceDBTokensBySpace
	}
}

// WithSpicedbCAPath returns an option that can set SpicedbCAPath on a SpiceDBOptions
func WithSpicedbCAPath(spicedbCAPath string) SpiceDBOptionsOption {
	return func(s *SpiceDBOptions) {
		s.SpicedbCAPath = spicedbCAPath
	}
}
