apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: authzed/spicedb-kubeapi-proxy:dev
  newName: kind.local/spicedb-kubeapi-proxy
  newTag: c90e5619e24d34a8cda2b306b9b42aedf615fe5021e1ff40ee80050f63bc5b80
kind: Kustomization
resources:
- proxy.yaml
- cert-manager.yaml
- client-ca.yaml
- client-cert.yaml
- http-cert.yaml
- issuer.yaml
