apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: authzed/spicedb-kubeapi-proxy:dev
  newName: kind.local/spicedb-kubeapi-proxy
  newTag: f2ed27188b9062886b40142ac724a55d9e3498d1945c5192e58aa797c4a23ded
kind: Kustomization
resources:
- proxy.yaml
