apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - rules.yaml
  name: rules
  namespace: spicedb-kubeapi-proxy
  options:
    disableNameSuffixHash: true
images:
- name: authzed/spicedb-kubeapi-proxy:dev
  newName: kind.local/spicedb-kubeapi-proxy
  newTag: 7b6c2489bde6add5e851d3cf2dffd7b85f40539cde75d9bcf86507793f7a785e
kind: Kustomization
resources:
- proxy.yaml
- cert-manager.yaml
- client-ca.yaml
- client-cert.yaml
- http-cert.yaml
- issuer.yaml
