apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: authzed/spicedb-kubeapi-proxy:dev
  newName: kind.local/spicedb-kubeapi-proxy
  newTag: 2d63ce5d46dc1e3ebf81e7c6466fe22756a36d17e82540629c2192a08a77b5db
kind: Kustomization
resources:
- proxy.yaml
