---
name: "Build & Test"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  merge_group:
    types:
      - "checks_requested"
jobs:
  paths-filter:
    runs-on: "ubuntu-latest"
    outputs:
      codechange: "${{ steps.code-filter.outputs.codechange }}"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "dorny/paths-filter@v3"
        id: "code-filter"
        with:
          filters: |
            codechange:
              - ".github/workflows/build-test.yaml"
              - "Dockerfile"
              - "go.mod"
              - "go.sum"
              - "cmd/**"
              - "magefiles/**"
              - "pkg/**"
              - "e2e/**"
              - "internal/**"
  build:
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-build@main"

  go-lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - name: "Lint Go"
        uses: "authzed/actions/golangci-lint@main"

  unit:
    name: "Unit"
    runs-on: "ubuntu-latest-4-cores"
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - name: "Unit tests"
        uses: "magefile/mage-action@v3"
        with:
          version: "latest"
          args: "test:unit"
      - name: "Upload coverage reports to Codecov"
        uses: "codecov/codecov-action@v5"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    name: "e2e Tests"
    runs-on: "ubuntu-latest-4-cores"
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - name: "e2e tests"
        uses: "magefile/mage-action@v3"
        with:
          version: "latest"
          args: "test:e2e"