---
name: "Pull Request Labeler"
on:  # yamllint disable-line rule:truthy
  pull_request_target:
  merge_group:
    types:
      - "checks_requested"
jobs:
  triage:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: "actions/labeler@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
